// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kinwqqfqfcytkwdxcidj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtpbndxcWZxZmN5dGt3ZHhjaWRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3ODAwNTYsImV4cCI6MjA2ODM1NjA1Nn0.Vis-vnmj0_9QMDpn7nC_SFo4u8Uqp0iBR2CCraUtR10";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});